CHEF_ROOT = ../../../install
CHEF_LIBS = $(CHEF_ROOT)/lib
CHEF_INC = $(CHEF_ROOT)/include
CHEF_BOOST_INC = $(CHEF_INC)/boost-1_35

CPPFLAGS = -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I$(CHEF_INC) -I$(CHEF_BOOST_INC)

LDFLAGS = -L$(CHEF_LIBS) -lphysics_toolkit -lmxyzptlk -lbeamline \
	-lbmlfactory -lintegrator -lfftw3 -lbasic_toolkit -lglib-2.0

