#!/bin/sh

cd "`dirname $0`" && \
echo "generating foborodobo32_lattice.xml"
synergia generate_foborodobo32_xml.py
echo "copying fnal_booster.xml from lattice/tests/lattices"
cp ../../../lattice/tests/lattices/fnal_booster.xml .
echo "copying fnal_debuncher.xml from lattice/tests/lattices"
cp ../../../lattice/tests/lattices/fnal_debuncher.xml .
echo "copying fnal_main_injector.xml from lattice/tests/lattices"
cp ../../../lattice/tests/lattices/fnal_main_injector.xml .
echo "generating fnal_main_injector.xml"
synergia generate_main_injector_xml.py
