#!/usr/bin/env python

from matplotlib.pylab import *
from loadfile import loadfile

x = loadfile("test6_out.dat")
figure(1)
subplot(2,1,1)
ylabel("beta x")
plot(x[:,0],x[:,1],label="PT")
plot(x[:,0],x[:,7],label="CHEF")
legend(loc=0)
subplot(2,1,2)
xlabel("s")
ylabel("PT-CHEF")
plot(x[:,0],x[:,1]-x[:,7],label="covariance")
plot(x[:,0],x[:,1]-x[:,5],label="twiss")
legend(loc=0)
savefig("betax.ps")
figure(2)
subplot(2,1,1)
ylabel("beta y")
plot(x[:,0],x[:,2],label="PT")
plot(x[:,0],x[:,8],label="CHEF")
legend(loc=0)
subplot(2,1,2)
xlabel("s")
ylabel("PT-CHEF")
plot(x[:,0],x[:,2]-x[:,8],label="covariance")
plot(x[:,0],x[:,2]-x[:,6],label="twiss")
legend(loc=0)
savefig("betay.ps")

figure(3)
subplot(2,1,1)
ylabel("dispersion")
plot(x[:,0],x[:,3],label="PT")
plot(x[:,0],x[:,9],label="CHEF")
legend(loc=0)
subplot(2,1,2)
xlabel("s")
ylabel("PT-CHEF")
plot(x[:,0],x[:,3]-x[:,9],label="covariance")
legend(loc=0)
savefig("dispersion.ps")
figure(4)
subplot(2,1,1)
ylabel("dispersion'")
plot(x[:,0],x[:,4],label="PT")
plot(x[:,0],x[:,10],label="CHEF")
legend(loc=0)
subplot(2,1,2)
xlabel("s")
ylabel("PT-CHEF")
plot(x[:,0],x[:,4]-x[:,10],label="covariance")
legend(loc=0)
savefig("disp_prime.ps")


show()
