[project]
name = "synergia2"
version = "2024.04.17"
description = "Synergia is a accelerator modeling and simulation package developped at Fermilab."
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
cmake = "cmake -S . -B build_pixi -DCMAKE_INSTALL_PREFIX=$(pwd)/install_pixi -DUSE_EXTERNAL_KOKKOS=OFF -DUSE_OPENPMD_IO=ON -DUSE_EXTERNAL_OPENPMD=OFF -DGSV=DOUBLE"
build = { cmd = "cmake --build build_pixi", depends_on = ["cmake"] }
install = { cmd = "cmake --install build_pixi", depends_on = ["build"] }
test = { cmd = "ctest --output-on-failure --test-dir build_pixi", depends_on = ["install"],env = { SYNINSTALL = "$(pwd)/install_pixi", LD_LIBRARY_PATH = "$SYNINSTALL/lib:$SYNINSTALL:lib64:$LD_LIBRARY_PATH",PYTHON_VERSION = "$(python3 -c 'import sys; print(str(sys.version[:4]))')",PYTHONPATH="$SYNINSTALL/lib:$SYNINSTALL/lib/python$PYTHON_VERSION/site-packages:$PYTHONPATH" } } 
test-rerun-failed = { cmd = "ctest -V --output-on-failure --rerun-failed --test-dir build_pixi", depends_on = ["install"],env = { SYNINSTALL = "$(pwd)/install_pixi", LD_LIBRARY_PATH = "$SYNINSTALL/lib:$SYNINSTALL:lib64:${LD_LIBRARY_PATH}",PYTHON_VERSION = "$(python3 -c 'import sys; print(str(sys.version[:4]))')",PYTHONPATH="$SYNINSTALL/lib:$SYNINSTALL/lib/python$PYTHON_VERSION/site-packages:$PYTHONPATH" } }
env-test = {cmd = "echo $PYTHONPATH", env = { SYNINSTALL = "$(pwd)/install_pixi", LD_LIBRARY_PATH = "$SYNINSTALL/lib:$SYNINSTALL:lib64:${LD_LIBRARY_PATH}", PYTHON_VERSION = "$(python3 -c 'import sys; print(str(sys.version[:4]))')",PYTHONPATH="$SYNINSTALL/lib:$SYNINSTALL/lib/python$PYTHON_VERSION/site-packages:$PYTHONPATH" } }
clean = "rm -rf build_pixi/ && rm -rf install_pixi/"

[dependencies]
python = ">=3.12.3,<3.13"
cmake = ">=3.29.5,<3.30"
h5py = { version = ">=3.11.0,<3.12", build = "mpi*" }
gsl = ">=2.7,<3"
fftw = { version = ">=3.3.10,<3.4", build = "mpi*" }
hdf5 = { version = ">=1.14.3,<1.15", build = "mpi*" }
pybind11 = ">=2.12.0,<2.13"
pytest = ">=8.2.2,<8.3"
numpy = ">=1.26.4,<1.27"
seaborn = ">=0.13.2,<0.14"
