[project]
name = "synergia2"
version = "2024.04.17"
description = "Synergia is a accelerator modeling and simulation package developped at Fermilab."
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
cmake = "cmake -S . -B build -DUSE_EXTERNAL_KOKKOS=OFF -DUSE_OPENPMD_IO=ON -DUSE_EXTERNAL_OPENPMD=OFF -DGSV=DOUBLE"
build = "cmake --build build"
test = "ctest --output-on-failure --test-dir build"
clean = "rm -rf build/"

[dependencies]
python = ">=3.12.3,<3.13"
cmake = ">=3.29.5,<3.30"
h5py = { version = ">=3.11.0,<3.12", build = "mpi*" }
gsl = ">=2.7,<3"
fftw = { version = ">=3.3.10,<3.4", build = "mpi*" }
hdf5 = { version = ">=1.14.3,<1.15", build = "mpi*" }
pybind11 = ">=2.12.0,<2.13"
pytest = ">=8.2.2,<8.3"
numpy = ">=1.26.4,<1.27"
seaborn = ">=0.13.2,<0.14"
