#!/usr/bin/env python
import numpy
from matplotlib import pylab

pylab.figure(0)
x0 = numpy.loadtxt('timingfodo.txt')
pylab.semilogy(x0[:,0], x0[:,1], label='chef')
pylab.semilogy(x0[:,0], x0[:,2], label='trigon')
pylab.legend()
pylab.title('100x fodo cell')
pylab.ylabel('time (seconds)')
pylab.xlabel('jet order')
pylab.ion()
pylab.show()
pylab.savefig('fodo.pdf')

pylab.figure(1)
x1 = numpy.loadtxt('timing.txt')
pylab.semilogy(x1[:,0], x1[:,1], label='chef')
pylab.semilogy(x1[:,0], x1[:,2], label='trigon')
pylab.legend()
pylab.title('5x foboodobo128 cell (no RF)')
pylab.ylabel('time (seconds)')
pylab.xlabel('jet order')
pylab.ion()
pylab.show()
pylab.savefig('norf.pdf')

pylab.figure(2)
x2 = numpy.loadtxt('timingwrf.txt')
pylab.semilogy(x2[:,0], x2[:,1], label='chef')
pylab.semilogy(x2[:,0], x2[:,2], label='trigon')
pylab.legend()
pylab.title('5x foborodobo128 cell (with RF)')
pylab.ylabel('time (seconds)')
pylab.xlabel('jet order')
pylab.ion()
pylab.show()
pylab.savefig('full.pdf')

pylab.figure(3)
pylab.semilogy(x0[:,0], x0[:,1], label='fodo chef')
pylab.semilogy(x0[:,0], x0[:,2], label='fodo trigon')
pylab.semilogy(x1[:,0], x1[:,1], label='no RF chef')
pylab.semilogy(x1[:,0], x1[:,2], label='no RF trigon')
pylab.semilogy(x2[:,0], x2[:,1], label='full chef')
pylab.semilogy(x2[:,0], x2[:,2], label='full trigon')
pylab.legend()
pylab.title('comparison')
pylab.ylabel('time (seconds)')
pylab.xlabel('jet order')
pylab.ion()
pylab.show()
pylab.savefig('comparison.pdf')
