/*****************************************************************************
*
* Copyright (c) 2000 - 2008, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-400142
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtCOMPASS_FNALFileFormat.C                           //
// ************************************************************************* //

#include <avtCOMPASS_FNALFileFormat.h>

#include <string>

#include <vtkFloatArray.h>
#include <vtkDoubleArray.h>
#include <vtkUnstructuredGrid.h>
#include <vtkCellType.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>

#include <InvalidVariableException.h>
#include <InvalidDBTypeException.h>

#include <DebugStream.h>

#define H5_USE_16_API
#include <hdf5.h>

using     std::string;

// ****************************************************************************
//  Method: avtCOMPASS_FNALFileFormat constructor
//
//  Programmer: ghweber -- generated by xml2avt
//  Creation:   Tue Mar 17 14:18:28 PST 2009
//
// ****************************************************************************

avtCOMPASS_FNALFileFormat::avtCOMPASS_FNALFileFormat(const char *filename)
    : avtSTSDFileFormat(filename)
{
    // INITIALIZE DATA MEMBERS
    //
}


// ****************************************************************************
//  Method: avtCOMPASS_FNALFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: ghweber -- generated by xml2avt
//  Creation:   Tue Mar 17 14:18:28 PST 2009
//
// ****************************************************************************

void
avtCOMPASS_FNALFileFormat::FreeUpResources(void)
{
}


// ****************************************************************************
//  Method: avtCOMPASS_FNALFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: ghweber -- generated by xml2avt
//  Creation:   Tue Mar 17 14:18:28 PST 2009
//
// ****************************************************************************

void
avtCOMPASS_FNALFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md)
{
    // Add particle mesh
    AddMeshToMetaData(md, string("particles"), AVT_POINT_MESH, 0, 1, 0, 3, 0);

    // Add variables for momentum components
    AddScalarVarToMetaData(md, string("px"), std::string("particles"), AVT_NODECENT);
    AddScalarVarToMetaData(md, string("py"), std::string("particles"), AVT_NODECENT);
    AddScalarVarToMetaData(md, string("pz"), std::string("particles"), AVT_NODECENT);
    AddScalarVarToMetaData(md, string("ID"), std::string("particles"), AVT_NODECENT);

    // Add expression to create a momentum vector from the individual components
    Expression momentum_expr;
    momentum_expr.SetName("momentum");
    momentum_expr.SetDefinition("{px, py, pz}");
    momentum_expr.SetType(Expression::VectorMeshVar);
    md->AddExpression(&momentum_expr);
}


// ****************************************************************************
//  Method: avtCOMPASS_FNALFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: ghweber -- generated by xml2avt
//  Creation:   Tue Mar 17 14:18:28 PST 2009
//
// ****************************************************************************

vtkDataSet *
avtCOMPASS_FNALFileFormat::GetMesh(const char *meshname)
{
    vtkUnstructuredGrid *ugrid = 0;

    if (strcmp(meshname, "particles") == 0)
    {
        hid_t file = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);
        if (file > 0)
        {
            hid_t dataSet = H5Dopen(file, "/particles");
            if ( dataSet > 0)
            {
                hid_t dataSpace = H5Dget_space(dataSet);
                if (H5Sis_simple(dataSpace))
                {
                    if (H5Sget_simple_extent_ndims(dataSpace) == 2)
                    {
                        hsize_t dims[2];
                        H5Sget_simple_extent_dims(dataSpace, dims, NULL);

                        if (dims[0] == 7)
                        {
                            vtkPoints *points = vtkPoints::New();
                            points->SetNumberOfPoints(dims[1]);
                            float *pts = (float *) points->GetVoidPointer(0);

                            float *data = new float[dims[0]*dims[1]]; // TODO: Implement in-place conversion between column and row major
                            hsize_t start[2] = { 0, 0 };
                            hsize_t stride[2] = { 2, 1 };
                            hsize_t count[2] = { 3, dims[1] };
                            H5Sselect_hyperslab(dataSpace, H5S_SELECT_SET, start, stride, count, 0);
                            hid_t memSpace = H5Screate_simple(2, count, 0);
                            H5Dread(dataSet, H5T_NATIVE_FLOAT, memSpace, dataSpace, H5P_DEFAULT, data);
                            H5Sclose(memSpace);
                            
                            // TODO: Implement in-place conversion between column and row major
                            for (int i=0; i<dims[1]; ++i)
                            {
                                pts[3*i+0] = data[          i];
                                pts[3*i+1] = data[  dims[1]+i];
                                pts[3*i+2] = data[2*dims[1]+i];
                            }
                            delete[] data;
                            
                            //
                            // Create a vtkUnstructuredGrid to contain the point cells.
                            //
                            ugrid = vtkUnstructuredGrid::New();
                            ugrid->SetPoints(points);
                            points->Delete();
                            ugrid->Allocate(dims[1]);
                            vtkIdType onevertex;
                            for(int i = 0; i < dims[1]; ++i)
                            {
                                onevertex = i;
                                ugrid->InsertNextCell(VTK_VERTEX, 1, &onevertex);
                            }
                        }
                        else
                        {
                            EXCEPTION1(InvalidDBTypeException, "Cannot be a "
                                   "COMPASS_FNAL file, since \"particles\" data "
                                   "set does not have exactly seven columns.");
                        }
                    }
                    else
                    {
                        EXCEPTION1(InvalidDBTypeException, "Cannot be a "
                                "COMPASS_FNAL file, since \"particles\" data set "
                                " does not have rank two.");
                    }
                }
                else
                {
                    EXCEPTION1(InvalidDBTypeException, "Cannot be a "
                            "COMPASS_FNAL file, since \"particles\" data set "
                            " does not have a simple data space.");
                }
                H5Sclose(dataSpace);
                H5Dclose(dataSet);
            }
            else
            {
                EXCEPTION1(InvalidDBTypeException, "Cannot be a COMPASS_FNAL file, since "
                        "it does not contain a \"particles\" data set.");
            }
            H5Fclose(file);
        }
        else
        {
            debug1 << "Couldn't open file " << filename << std::endl;
            EXCEPTION1(InvalidDBTypeException, "Cannot be a COMPASS_FNAL file, since "
                    "it is not even an HDF5 file.");
        }
    }
    else
    {
        // No mesh name that we recognize.
        EXCEPTION1(InvalidVariableException, meshname);
    }
    return ugrid;
}


// ****************************************************************************
//  Method: avtCOMPASS_FNALFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: ghweber -- generated by xml2avt
//  Creation:   Tue Mar 17 14:18:28 PST 2009
//
// ****************************************************************************

vtkDataArray *
avtCOMPASS_FNALFileFormat::GetVar(const char *varname)
{
    vtkFloatArray *array = 0;
    int varIdx = -1;

    if (strcmp(varname, "px") == 0)
        varIdx = 1;
    else if (strcmp(varname, "py") == 0)
        varIdx = 3;
    else if (strcmp(varname, "pz") == 0)
        varIdx = 5;
    else if (strcmp(varname, "ID") == 0)
        varIdx = 6;
    else
        EXCEPTION1(InvalidVariableException, varname);

    hid_t file = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);
    if (file > 0)
    {
        hid_t dataSet = H5Dopen(file, "/particles");
        if ( dataSet > 0)
        {
            hid_t dataSpace = H5Dget_space(dataSet);
            if (H5Sis_simple(dataSpace))
            {
                if (H5Sget_simple_extent_ndims(dataSpace) == 2)
                {
                    hsize_t dims[2];
                    H5Sget_simple_extent_dims(dataSpace, dims, NULL);

                    if (dims[0] == 7)
                    {
                        array = vtkFloatArray::New();
                        array->SetNumberOfTuples(dims[1]);
                        float *vals = (float *) array->GetVoidPointer(0);
                        hsize_t start[2] = { varIdx, 0 };
                        hsize_t count[2] = { 1, dims[1] };
                        H5Sselect_hyperslab(dataSpace, H5S_SELECT_SET, start, 0, count, 0);
                        hid_t memSpace = H5Screate_simple(2, count, 0);
                        H5Dread(dataSet, H5T_NATIVE_FLOAT, memSpace, dataSpace, H5P_DEFAULT, vals);
                        H5Sclose(memSpace);
                    }
                    else
                    {
                        EXCEPTION1(InvalidDBTypeException, "Cannot be a "
                                "COMPASS_FNAL file, since \"particles\" data "
                                "set does not have exactly seven columns.");
                    }
                }
                else
                {
                    EXCEPTION1(InvalidDBTypeException, "Cannot be a "
                            "COMPASS_FNAL file, since \"particles\" data set "
                            " does not have rank two.");
                }
            }
            else
            {
                EXCEPTION1(InvalidDBTypeException, "Cannot be a "
                        "COMPASS_FNAL file, since \"particles\" data set "
                        " does not have a simple data space.");
            }
            H5Sclose(dataSpace);
            H5Dclose(dataSet);
        }
        else
        {
            EXCEPTION1(InvalidDBTypeException, "Cannot be a COMPASS_FNAL file, since "
                    "it does not contain a \"particles\" data set.");
        }
        H5Fclose(file);
    }
    else
    {
        debug1 << "Couldn't open file " << filename << std::endl;
        EXCEPTION1(InvalidDBTypeException, "Cannot be a COMPASS_FNAL file, since "
                "it is not even an HDF5 file.");
    }

    return array;
}


// ****************************************************************************
//  Method: avtCOMPASS_FNALFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: ghweber -- generated by xml2avt
//  Creation:   Tue Mar 17 14:18:28 PST 2009
//
// ****************************************************************************

vtkDataArray *
avtCOMPASS_FNALFileFormat::GetVectorVar(const char *varname)
{
    EXCEPTION1(InvalidVariableException, varname);
}
