#!/bin/sh

cd `dirname $0`
cd ..

#~ local_dir="`dirname $0`"
#~ SYNERGIA2DIR="$local_dir"
#~ export SYNERGIA2DIR
chef_dir="/home/amundson/work/synergia2-base/install/lib"
impact_dir="$local_dir/../impact/Forthon_Interfaces"
#~ for dir in $local_dir $chef_dir $impact_dir
for dir in $impact_dir
do
    PYTHONPATH="$dir:$PYTHONPATH"
done
export PYTHONPATH

rm -rf doc/html
epydoc "$1" --html -o doc/html --graph classtree --dotpath=/usr/bin/dot --exclude="MLab.*" synergia s2_fish
