#ifndef FODO_CXX_OPTIONS_H_
#define FODO_CXX_OPTIONS_H_
#include <string>

// this file was automatically generated by the command
//     synergia fodo_cxx_options.py --create-cxx-options-source
// DO NOT EDIT

struct Fodo_cxx_options
{
    Fodo_cxx_options(int argc, char **argv);
    int gridx;
    int gridy;
    int gridz;
    int macroparticles;
    double real_particles;
    int turns;
};
#endif /* FODO_CXX_OPTIONS_H_ */
