#!/bin/sh
#PBS -o synergia.out
#PBS -e synergia.err
#PBS -l nodes=@@numproc@@
#PBS -A usertest
#PBS -m abe
#PBS -M egstern@fnal.gov

# This script is an appropriate template for running PBS jobs on the
# jpsi cluster.  jpsi nodes have 8 cores.  numproc as passed to the
# synergia script is the number of nodes.  The number of cpus is 8
# times that

echo PBS_NODEFILE is "$PBS_NODEFILE"
if [ -n "$PBS_NODEFILE" ]
then
    echo "begin nodes"
    cat $PBS_NODEFILE
    echo "end nodes"
fi

MPI_HOME=/usr/local/mvapich-egs

export PATH=${MPI_HOME}/bin:$PATH
export LD_LIBRARY_PATH=${MPI_HOME}/lib/shared:$LD_LIBRARY_PATH

. "@@synergia2dir@@/../../setup.sh"


LD_LIBRARY_PATH=`synergia --ldlibrarypath`

export LD_LIBRARY_PATH

SYNERGIA2DIR=@@synergia2dir@@
export SYNERGIA2DIR

PYTHONPATH=`synergia --pythonpath`
export PYTHONPATH

export HDF5_DISABLE_VERSION_CHECK=2

NP=`expr 8 \* @@numproc@@`

echo "PATH: $PATH"
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
echo "PYTHONPATH: $PYTHONPATH"

cd @@jobdir@@
echo "Job start at `date`"
${MPI_HOME}/bin/mpirun_rsh_8 -np $NP $SYNERGIA2DIR/../../install/bin/synergia @@script@@ @@args@@
echo "Job end at `date`"

