#!/bin/sh
#PBS -o synergia.out
#PBS -e synergia.err
#PBS -l nodes=@@numnode@@:@@queue@@
__walltime{{#PBS -l walltime=@@walltime@@}}{{}}__
__queue{{#PBS -q @@queue@@}}{{}}__
__account{{#PBS -A @@account@@}}{{}}__

# This script is an appropriate template for running PBS jobs on the
# wilson cluster.

echo PBS_NODEFILE is "$PBS_NODEFILE"
if [ -n "$PBS_NODEFILE" ]
then
    echo "begin nodes"
    cat $PBS_NODEFILE
    echo "end nodes"
fi
MPI_HOME=/usr/local/openmpi

export PATH=${MPI_HOME}/bin:$PATH
export LD_LIBRARY_PATH=${MPI_HOME}/lib:$LD_LIBRARY_PATH

. @@setupsh@@

cd $PBS_O_WORKDIR
echo "Job start at `date`"
${MPI_HOME}/bin/mpirun  -np @@numproc@@ --map-by node --bind-to numa @@synergia_resume_executable@@
echo "Job end at `date`"


