BOOST_INCS = -I/home3/egstern/synergia2-master/install/include/boost-1_38

CHEF_INCS = -I/home3/egstern/synergia2-master/install/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include

LDFLAGS = -L/home3/egstern/synergia2-master/install/lib -lphysics_toolkit -lbeamline -lbmlfactory -L/lib -lglib-2.0 -lbasic_toolkit -lmxyzptlk

CXXFLAGS = $(BOOST_INCS) $(CHEF_INCS)

CompactionFactor: CompactionFactor.o

track_long: track_long.o
