#!/bin/sh
#PBS -o synergia.out
#PBS -e synergia.err
#PBS -l nodes=@@numproc@@

echo PBS_NODEFILE is "$PBS_NODEFILE"
if [ -n "$PBS_NODEFILE" ]
then
    echo "begin nodes"
    cat $PBS_NODEFILE
    echo "end nodes"
fi
export PATH=/usr/local/openmpi-1.2.3/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/openmpi-1.2.3/lib:$LD_LIBRARY_PATH

. "@@synergia2dir@@/../../setup.sh"
LD_LIBRARY_PATH="/usr/local/lib/octave-2.1.72:@@synergia2dir@@/extra_libs:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH

SYNERGIA2DIR=@@synergia2dir@@
export SYNERGIA2DIR

PYTHONPATH=$SYNERGIA2DIR
export PYTHONPATH

cd @@jobdir@@
exec mpirun -np @@numproc@@ "$SYNERGIA2DIR"/synergia_local @@script@@ @@args@@


