#!/bin/sh
#PBS -o synergia.out
#PBS -e synergia.err
#PBS -l nodes=@@numproc@@:ppn=4

# This script is an appropriate template for running PBS jobs on the
# rfsims cluster.  Each node has 4 processors and PBS is configured to
# only allocate full nodes.  The numproc= value that is pass to the
# job script refers to the number of nodes.

echo PBS_NODEFILE is "$PBS_NODEFILE"
if [ -n "$PBS_NODEFILE" ]
then
    echo "begin nodes"
    cat $PBS_NODEFILE
    echo "end nodes"
fi
MPI_HOME=${HOME}/synergia2-devel_1_0/install

export PATH=${MPI_HOME}/bin:$PATH
export LD_LIBRARY_PATH=${MPI_HOME}/lib:$LD_LIBRARY_PATH

. "@@synergia2dir@@/../../setup.sh"
LD_LIBRARY_PATH="/usr/local/lib/octave-2.1.72:@@synergia2dir@@/extra_libs:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH

SYNERGIA2DIR=@@synergia2dir@@
export SYNERGIA2DIR

PYTHONPATH=$SYNERGIA2DIR
export PYTHONPATH

export HDF5_DISABLE_VERSION_CHECK=2

cd @@jobdir@@
echo "Job start at `date`"
${MPI_HOME}/bin/mpirun  "$SYNERGIA2DIR"/synergia-local @@script@@ @@args@@
echo "Job end at `date`"

