#!/bin/sh
#PBS -o synergia.out
#PBS -e synergia.err
#PBS -l nodes=@@numnode@@
#PBS -A usertest

# This script is an appropriate template for running PBS jobs on the
# tev cluster.

echo PBS_NODEFILE is "$PBS_NODEFILE"
if [ -n "$PBS_NODEFILE" ]
then
    echo "begin nodes"
    cat $PBS_NODEFILE
    echo "end nodes"
fi
MPI_HOME=/usr/local/openmpi

export PATH=${MPI_HOME}/bin:$PATH
export PATH=/usr/local/python-2.7.0/bin:$PATH
export LD_LIBRARY_PATH=${MPI_HOME}/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/python-2.7.0/lib:$LD_LIBRARY_PATH

LD_LIBRARY_PATH="@@synergia2dir@@/extra_libs:$LD_LIBRARY_PATH"

. "@@synergia2dir@@/../../setup.sh"

SYNERGIA2DIR=@@synergia2dir@@
export SYNERGIA2DIR

export HDF5_DISABLE_VERSION_CHECK=2

cd @@jobdir@@
echo "Job start at `date`"
${MPI_HOME}/bin/mpirun -np @@numproc@@ synergia @@script@@ @@args@@
echo "Job end at `date`"

