#!/bin/sh

cd @@jobdir@@

qsub -n @@numproc@@ --mode vn -t 00:10:00 -M 'amundson@fnal.gov' -A ComPASSatBGP -O synergia --env OMP_NUM_THREADS=1:PYTHONPATH="`synergia --pythonpath`":LD_LIBRARY_PATH="`synergia --ldlibrarypath`":SYNERGIA2DIR=@@synergia2dir@@ /bgsys/drivers/ppcfloor/gnu-linux/bin/python @@script@@ @@args@@

