#!/bin/sh
#synergia_workflow_submitter:/bin/sh
cd @@jobdir@@ && \
(time mpirun -np @@numproc@@ @@synergia_executable@@ @@script@@ @@args@@ 1> synergia.out 2> synergia.err; \
echo "synergia finished with exit status $?")


