function(add_python_extension MODNAME)
  # Define the supported set of keywords
  cmake_parse_arguments(APE "" "" "LIBRARIES" ${ARGN})
  set(FILES ${APE_UNPARSED_ARGUMENTS})
  add_library(${MODNAME} MODULE ${FILES})
  set_target_properties(${MODNAME} PROPERTIES PREFIX "")
  if (APE_LIBRARIES)
    target_link_libraries(${MODNAME} ${APE_LIBRARIES})
  endif()
  target_include_directories(${MODNAME} PRIVATE ${MY_PYTHON_INCLUDE_DIRECTORY})
  target_link_libraries(${MODNAME} ${MY_BOOST_PYTHON_LIBRARY} ${MY_PYTHON_LIBRARY})
endfunction(add_python_extension)
