macro(smart_include_directories INCLUDE_DIRECTORIES)
    set(_need_usr_local OFF)
    set(_need_usr OFF)
    foreach(_dir ${INCLUDE_DIRECTORIES})
        if("${_dir}" STREQUAL "/usr/local/include")
            set(_need_usr_local ON)
        elseif("${_dir}" STREQUAL "/usr/include")
            set(_need_usr ON)
        else("${_dir}" STREQUAL "/usr/local/include")
            include_directories(AFTER ${_dir})
        endif("${_dir}" STREQUAL "/usr/local/include")
    endforeach(_dir)
    if(_need_usr_local)
        include_directories(AFTER "/usr/local/include")
    endif(_need_usr_local)
    if(_need_usr)
        include_directories(AFTER "/usr/include")
    endif(_need_usr)
endmacro(smart_include_directories)
