#!/usr/bin/env python

import workflow

myopts = workflow.Options("mi")
#~ myopts.add("current",0.5,"current",float)
myopts.add("transverse",0,"longitudinally uniform beam",int)
myopts.add("periodic", 0, "longitudinally periodic bunch and solver", int)
myopts.add("adjust_zlength_to_freq", 0, "automatically set z length based on scaling frequency", int)
myopts.add("solver", "s2_fish_3d", "space charge solver", str)
myopts.add("maporder",2,"map order",int)
myopts.add("dpop",1.0e-20,"(delta p)/p",float)
myopts.add("dpopoffset", 0.0, "offset in dpop (am: ! -duop)", float)
myopts.add("kicks",10,"kicks per line",int)
myopts.add("turns",4,"number of turns",int)
myopts.add("latticefile","mi20-egs.lat","",str)
myopts.add("tgridnum",16,"transverse grid cells",int)
myopts.add("lgridnum",64,"",int)
myopts.add("scaling_frequency", 52.8124e6, "scaling frequency (If this matters there is a problem)", float)
myopts.add("xoffset",1.0e-6,"",float)
myopts.add("yoffset",-1.2e-6,"",float)
myopts.add("zoffset",0.0,"offset in z", float)
myopts.add("xpoffset", 0, "offset in x-prime", float)
myopts.add("ypoffset", 0, "offset in y-prime", float)
myopts.add("emittance",0.26e-6,"transverse (geometric) emittance",float)
myopts.add("bunchlen", 0.75, "rms bunch length", float)
myopts.add("space_charge",1,"",int)
myopts.add("impedance",0,"",int)
myopts.add("energy",8.949321,"",float)
myopts.add("partpercell",1,"",float)
myopts.add("bunches",1,"",int)
myopts.add("bunchnp",1.0e11,"number of particles per bunch",float)
myopts.add("pipe_radius", 0.025, "pipe radius", float)
myopts.add("dump", 0, "dump particles every n turns", int)
myopts.add("dump_freq", 1, "the number of turns between particle dump", int)
job_mgr = workflow.Job_manager("mi.py", myopts,
                                  [myopts.get("latticefile")])
