
name: CI:ubuntu-pixi-conda

on:
  push:
    branches: [ devel3 ]
    paths-ignore:
      - 'wiki/**'
  pull_request:
    branches: [ devel3 ]
    paths-ignore:
      - 'wiki/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        
    - name: build_and_test
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.23.0
        cache: true
    - run: |
        pixi run cmake
        pixi run build
        pixi run test
